### ISSUE TITLE
启动sofastack-guides / kc-sofastack-dynamic-demo工程失败

### ISSUE THREAD

**Issue by ivanljc2017** [sofastack-guides/kc-sofastack-dynamic-demo#7]
sofastack-guides / kc-sofastack-dynamic-demo导入eclipse，按步骤生成jar后，执行 java -jar dynamic-stock-mng/target/dynamic-stock-mng-1.0.0.jar时出错如下：
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: Master biz should be configured when deploy multi biz.
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:135)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:91)
        ... 8 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: Master biz should be configured when deploy multi biz.
        at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.process(HandleArchiveStage.java:133)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: Master biz should be configured when deploy multi biz.
        at com.alipay.sofa.ark.common.util.AssertUtils.isFalse(AssertUtils.java:84)
        at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.process(HandleArchiveStage.java:121)
        ... 11 more

**Comment by Crotion** [comment]
If you got error Master biz should be configured when deploy multi biz, please add jvm parameter -Dcom.alipay.sofa.ark.master.biz=sample-bundle.
