### ISSUE TITLE
启动StockMngApplication提示Telnet port should be positive integer

### ISSUE THREAD

**Issue by Gred01** [sofastack-guides/kc-sofastack-dynamic-demo#8]
具体错误如下
Exception in thread "main" java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:49)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.sofastack.stockmng.StockMngApplication.main(StockMngApplication.java:10)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:59)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArk(ArkApplicationStartListener.java:55)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:41)
	... 11 more
Caused by: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.thread.IsolatedThreadGroup.rethrowUncaughtException(IsolatedThreadGroup.java:50)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:55)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:68)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Telnet port should be positive integer.
	at com.alipay.sofa.ark.common.util.AssertUtils.isTrue(AssertUtils.java:66)
	at com.alipay.sofa.ark.container.session.StandardTelnetServerImpl.run(StandardTelnetServerImpl.java:99)
	at com.alipay.sofa.ark.container.session.StandardTelnetServerImpl.init(StandardTelnetServerImpl.java:193)
	at com.alipay.sofa.ark.container.service.ArkServiceContainer.start(ArkServiceContainer.java:86)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:133)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:96)
	... 14 more

**Comment by Gred01** [comment]
费了好久去看了源码，才知道启动时会去启动TelenetService来监听链接，虽然不知道有什么用，先关掉了。在启动时增加参数【-Dsofa.ark.telnet.server.enable=false】
